{{- if .Values.microServices.meetupSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: meetup-secret
type: Opaque
data:
  password: {{ .Values.meetup.gpt.password | default (randAlphaNum 32) | b64enc | quote }}
{{- end -}}