{{- if .Values.microServices.transformer -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meetup
  name: meetup-service
spec:
  type: {{ .Values.service.type }}
{{- if (eq .Values.service.type "ClusterIP") }}
{{- end }}
  ports:
    - port: 80
      targetPort: 7000
      protocol: TCP
      name: http
{{- if (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.whiserPort }}
{{- end }}
  selector:
    service: meetup
    app: meetup
    release: {{ .Release.Name }}
{{- end -}}